name: CI

on:
  push:
    branches: [ master ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: 11

    - name: Build with Maven
      run: mvn clean install

    - name: Run tests with Maven
      run: mvn test

    - name: Deploy to Maven repository
      uses: maven-publish/action@v1
      with:
        server-id: my-maven-server
        repo-url: https://my-maven-repo.com/repository/maven-releases/
        distribution: repoUrl
